FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Kitabisa

API documentation for Kitabisa White Label

## Auth [/auth]

### Register [POST /auth/register]

+ Request (application/json)

        {
            "name": "User Skyshi",
            "email": "user@skyshi.com"
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {
                "token": "b78f3ec3494ba1a1809c918efff8b21f"
            }
        }

### Account Activation [POST /auth/register/activation]

+ Request (application/json)

        {
            "token": "b78f3ec3494ba1a1809c918efff8b21f",
            "password": "12345678"
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {}
        }

### Login [POST /auth/login]

+ Request (application/json)

        {
            "email": "user@skyshi.com",
            "password": "12345678"
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {}
        }

### Login Social [POST /auth/login/social]

+ Request (application/json)

        {
            "provider_name": "Facebook",
            "provider_uid": "12345678",
            "access_token": "EAAViKAqZCMswBAM1UqlZBZAF"
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {
                "_id": "5a67f684e1f7485ff03b2f6b",
                "name": "User Skyshi",
                "email": "user@skyshi.com"
                "phone": "081222333444",
                "photo_profile": "url",
                "location": "id",
                "address": "Tampomas no 9, Sleman"
            }
        }

### Forgot Password [POST /auth/password/forgot]

+ Request (application/json)

        {
            "email": "user@skyshi.com"
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {}
        }

### Reset Password [POST /auth/password/reset]

+ Request (application/json)

        {
            "token": "b78f3ec3494ba1a1809c918efff8b21f",
            "password": "12345678"
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {}
        }

## Campaign [/campaigns]

### Create Campaign [POST]

+ Request (application/json)

        {
            "title": "Bencana alam Tambora",
            "link": "https://kitabisa.com/bencana-alam-tambora",
            "target": 500000000,
            "deadline": 1516781054,
            "category_id": "5a67f684e1f7485ff03b2f6b",
            "location": "Sleman, Yogyakarta",
            "main_image": "",
            "main_video": "https://youtube.com",
            "short_description": "Lorem ipsum dolor sit amet",
            "description": "Lorem ipsum dolor sit amet",
            "is_verified": false,
            "is_active": false
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {}
        }

### List Campaign [GET /campaigns?page={page}&limit={limit}&q={query}&category_id={category_id}]

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": [
                {
                    "title": "Bencana alam Tambora",
                    "link": "https://kitabisa.com/bencana-alam-tambora",
                    "target": 500000000,
                    "deadline": 1516781054,
                    "category_id": "5a67f684e1f7485ff03b2f6b",
                    "location": "Sleman, Yogyakarta",
                    "main_image": "",
                    "main_video": "https://youtube.com",
                    "short_description": "Lorem ipsum dolor sit amet",
                    "description": "Lorem ipsum dolor sit amet",
                    "is_verified": true,
                    "is_active": true
                }
            ]
        }

### Detail Campaign [GET /campaigns/id={id}]

+ Parameters
    + id: "5a67f684e1f7485ff03b2f6b" (string)

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {
                "_id": "5a67f684e1f7485ff03b2f6b",
                "title": "Bencana alam Tambora",
                "link": "https://kitabisa.com/bencana-alam-tambora",
                "target": 500000000,
                "deadline": 1516781054,
                "category_id": "5a67f684e1f7485ff03b2f6b",
                "location": "Sleman, Yogyakarta",
                "main_image": "",
                "main_video": "https://youtube.com",
                "short_description": "Lorem ipsum dolor sit amet",
                "description": "Lorem ipsum dolor sit amet",
                "is_verified": true,
                "is_active": true
            }
        }

### Update Campaign [PUT /campaigns/id={id}]

+ Parameters
    + id: "5a67f684e1f7485ff03b2f6b" (string)

+ Request (application/json)

        {
            "title": "Bencana alam Tambora",
            "link": "https://kitabisa.com/bencana-alam-tambora",
            "target": 500000000,
            "deadline": 1516781054,
            "category_id": "5a67f684e1f7485ff03b2f6b",
            "location": "Sleman, Yogyakarta",
            "main_image": "",
            "main_video": "https://youtube.com",
            "short_description": "Lorem ipsum dolor sit amet",
            "description": "Lorem ipsum dolor sit amet",
            "is_verified": true,
            "is_active": false
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {}
        }

### Delete Campaign [DELETE /campaigns/id={id}]

+ Parameters
    + id: "5a67f684e1f7485ff03b2f6b" (string)

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {}
        }

### Campaign Donate [POST /campaigns/id={id}/donate]

+ Parameters
    + id: "5a67f684e1f7485ff03b2f6b" (string)

+ Request (application/json)

        {
            "amount": "Bencana alam Tambora",
            "comment": "https://kitabisa.com/bencana-alam-tambora",
            "payment_method_id": 1
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {}
        }

## Campaign [/payments]

### Callback API [POST]

+ Request (application/json)

        {
            "campaign_id": "5a67f684e1f7485ff03b2f6b",
            "user_id": "5a67f684e1f7485ff03b2f6b",
            "status": "SUCCESS"
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {}
        }
        
## User [/user]

### Get Profile [GET]

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {
                "_id": "5a67f684e1f7485ff03b2f6b",
                "name": "User Skyshi",
                "email": "user@skyshi.com"
                "phone": "081222333444",
                "photo_profile": "url",
                "location": "id",
                "address": "Tampomas no 9, Sleman"
            }
        }

### Update Profile [PUT]

+ Request (application/json)

        {
            "name": "User Skyshi",
            "phone": "081222333444",
            "photo_profile": "",
            "location": "id",
            "address": "Tampomas no 9, Sleman"
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {}
        }

### Get Donations [GET /user/donations?page={page}&limit={limit}&q={query}&category_id={category_id}]

+ Parameters
    + page: 1 (number)
    + limit: 10 (number)
    + query: "bencana" (string)
    + category_id: "5a67f684e1f7485ff03b2f6b" (string)

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": [
                {
                    "campaign_id": "5a67f684e1f7485ff03b2f6b",
                    "campaign": {
                        "title": "Bencana alam tambora"
                    },
                    "amount": 10000,
                    "message": "Semoga Berkah"
                }
            ]
        }
        
## Generator Example [/generator]

### Auth [POST /generator/auth/login]

+ Request (application/json)

        {
            "username": "skyshi",
            "password": "skyshi"
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {
                "name": "admin",
                "email": "developer@skyshi.com",
                "token" : "23423sfsdfsvfvfve223r32rdvvdfvdv"
            }
        }

### Book List [GET /generator/books?filter={filter}&pagination={pagination}&sort={sort}]
+ Parameters
    + filter: {"q":"search"} (object)
    + pagination: {"page": 1, "perPage": 10} (object)
    + sort: {"field": "name", "order":"ASC"} (object)

+ Response 200 (application/json)

    + Headers
        
            X-Total-Count: 10,
            Access-Control-Expose-Headers: X-Total-Count
            
    + Body

            
            [
                {
                    "id" : 1,
                    "name" : "book",
                    "image" : "http://lorempixel.com/400/200",
                    "category": {
                        "id" : "1",
                        "name" : "novel"
                    },
                    "writer" : {
                        "id" : "1",
                        "name" : "john doe"
                    },
                    "created_at" : 223432423,
                    "updated_at" : 342342424
                },
                {
                    "id" : 2,
                    "name" : "book",
                    "image" : "http://lorempixel.com/400/200",
                    "category": {
                        "id" : "1",
                        "name" : "novel"
                    },
                    "writer" : {
                        "id" : "1",
                        "name" : "john doe"
                    },
                    "created_at" : 223432423,
                    "updated_at" : 342342424
                },
                {
                    "id" : 3,
                    "name" : "book",
                    "image" : "http://lorempixel.com/400/200",
                    "category": {
                        "id" : "1",
                        "name" : "novel"
                    },
                    "writer" : {
                        "id" : "1",
                        "name" : "john doe"
                    },
                    "created_at" : 223432423,
                    "updated_at" : 342342424
                },
                {
                    "id" : 4,
                    "name" : "book",
                    "image" : "http://lorempixel.com/400/200",
                    "category": {
                        "id" : "1",
                        "name" : "novel"
                    },
                    "writer" : {
                        "id" : "1",
                        "name" : "john doe"
                    },
                    "created_at" : 223432423,
                    "updated_at" : 342342424
                },
                {
                    "id" : 5,
                    "name" : "book",
                    "image" : "http://lorempixel.com/400/200",
                    "category": {
                        "id" : "1",
                        "name" : "novel"
                    },
                    "writer" : {
                        "id" : "1",
                        "name" : "john doe"
                    },
                    "created_at" : 223432423,
                    "updated_at" : 342342424
                },
                {
                    "id" : 6,
                    "name" : "book",
                    "image" : "http://lorempixel.com/400/200",
                    "category": {
                        "id" : "1",
                        "name" : "novel"
                    },
                    "writer" : {
                        "id" : "1",
                        "name" : "john doe"
                    },
                    "created_at" : 223432423,
                    "updated_at" : 342342424
                },
                {
                    "id" : 7,
                    "name" : "book",
                    "image" : "http://lorempixel.com/400/200",
                    "category": {
                        "id" : "1",
                        "name" : "novel"
                    },
                    "writer" : {
                        "id" : "1",
                        "name" : "john doe"
                    },
                    "created_at" : 223432423,
                    "updated_at" : 342342424
                },
                {
                    "id" : 8,
                    "name" : "book",
                    "image" : "http://lorempixel.com/400/200",
                    "category": {
                        "id" : "1",
                        "name" : "novel"
                    },
                    "writer" : {
                        "id" : "1",
                        "name" : "john doe"
                    },
                    "created_at" : 223432423,
                    "updated_at" : 342342424
                },
                {
                    "id" : 9,
                    "name" : "book",
                    "image" : "http://lorempixel.com/400/200",
                    "category": {
                        "id" : "1",
                        "name" : "novel"
                    },
                    "writer" : {
                        "id" : "1",
                        "name" : "john doe"
                    },
                    "created_at" : 223432423,
                    "updated_at" : 342342424
                },
                {
                    "id" : 10,
                    "name" : "book",
                    "image" : "http://lorempixel.com/400/200",
                    "category": {
                        "id" : "1",
                        "name" : "novel"
                    },
                    "writer" : {
                        "id" : "1",
                        "name" : "john doe"
                    },
                    "created_at" : 223432423,
                    "updated_at" : 342342424
                }
            ]

### Book Detail [GET /generator/books/{id}]
+ Parameters
    + id: "1" (string)

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {
                "name" : "book",
                "image" : "http://lorempixel.com/400/200",
                "description":"dummy text",
                "category": {
                    "id" : "1",
                    "name" : "novel"
                },
                "writer" : {
                    "id" : "1",
                    "name" : "john doe"
                },
                "created_at" : 223432423,
                "updated_at" : 342342424
            }
        }
        
### Book Save [POST /generator/books]

+ Response 200 (application/json)

        {
           "id": 10
        }


### Book Update [PUT /generator/books/{id}]
+ Parameters
    + id: "1" (string)
    
+ Request (application/json)

        {
            "name": "book update",
            "image" : "http://lorempixel.com/400/200",
            "desc" : "test",
            "category_id": "2",
            "writer_id": "2"
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Update Success",
            "data": {}
        }

### Book Delete [DELETE /generator/books/{id}]
+ Parameters
    + id: "1" (string)

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Delete Success",
            "data": {}
        }
        
### Category List [GET /generator/categories]

+ Response 200 (application/json)

    + Headers
        
            X-Total-Count: 5,
            Access-Control-Expose-Headers: X-Total-Count
            
    + Body

            [
                {
                    "id": "1",
                    "name": "category 1"
                },
                {
                    "id": "2",
                    "name": "category 2"
                },
                {
                    "id": "3",
                    "name": "category 3"
                },
                {
                    "id": "4",
                    "name": "category 4"
                },
                {
                    "id": "5",
                    "name": "category 5"
                }
            ]
        
### Category Detail [GET /generator/categories/{id}]
+ Parameters
    + id: "1" (string)
    

+ Response 200 (application/json)

        {
            "id": "4",
            "name": "category 4"
        }


### Writer List [GET /generator/writers]

+ Response 200 (application/json)

    + Headers
        
            X-Total-Count: 5,
            Access-Control-Expose-Headers: X-Total-Count
            
    + Body

            [
                {
                    "id": "1",
                    "name": "write 1"
                },
                {
                    "id": "2",
                    "name": "write 2"
                },
                {
                    "id": "3",
                    "name": "write 3"
                },
                {
                    "id": "4",
                    "name": "write 4"
                },
                {
                    "id": "5",
                    "name": "write 5"
                }
            ]

### Writer Detail [GET /generator/writers/{id}]
+ Parameters
    + id: "1" (string)
    

+ Response 200 (application/json)

        {
            "id": "4",
            "name": "write 4"
        }

### Social Login [POST /generator/auth/social]
+ Request (application/json)

        {
            "service_provice_name": "facebook",
            "access_token" : "12312ejkfjksdvnldvndlfvkdflvdvn"
        }

+ Response 200 (application/json)

        {
            "email": "test@gmail.com",
            "name": "write 4",
            "id": "CALPsaC1QVmnQd9SsOBdAsLONDg7HCXfJl4xc6OcAmA6RNlZN9pllsBeGJ03m02W"
        }
        


### List All Questions [GET /datatables]

+ Response 200 (application/json)

        {
            "meta": {
                "page": 1,
                "pages": 35,
                "perpage": 10,
                "total": 350,
                "sort": "asc",
                "field": "ShipDate"
            },
            "data": [
                {
                    "RecordID": 10,
                    "OrderID": "55154-5393",
                    "ShipCountry": "NG",
                    "ShipCity": "Sapele",
                    "ShipName": "Moen, Kertzmann and Mills",
                    "ShipAddress": "1 Nancy Junction",
                    "CompanyEmail": "epere9@sina.com.cn",
                    "CompanyAgent": "Ely Pere",
                    "CompanyName": "Jacobi, O'Conner and Kuhlman",
                    "Currency": "NGN",
                    "Notes": "adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula",
                    "Department": "Shoes",
                    "Website": "whitehouse.gov",
                    "Latitude": 5.8750769,
                    "Longitude": 5.6931356,
                    "ShipDate": "1\/1\/2016",
                    "PaymentDate": "2017-06-20 10:42:35",
                    "TimeZone": "Africa\/Lagos",
                    "Status": 3,
                    "Type": 1,
                    "TotalPayment": "88,211.68 NGN"
                },
                {
                    "RecordID": 263,
                    "OrderID": "43406-0032",
                    "ShipCountry": "US",
                    "ShipCity": "Fort Pierce",
                    "ShipName": "Moore-Schaden",
                    "ShipAddress": "451 Fuller Junction",
                    "CompanyEmail": "tdefau7a@google.pl",
                    "CompanyAgent": "Tristan Defau",
                    "CompanyName": "Mayer and Sons",
                    "Currency": "USD",
                    "Notes": "mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus",
                    "Department": "Music",
                    "Website": "cornell.edu",
                    "Latitude": 27.3980151,
                    "Longitude": -80.3714326,
                    "ShipDate": "1\/1\/2017",
                    "PaymentDate": "2017-05-21 01:45:57",
                    "TimeZone": "America\/New_York",
                    "Status": 2,
                    "Type": 2,
                    "TotalPayment": "7,105.23 USD"
                },
                {
                    "RecordID": 77,
                    "OrderID": "68016-527",
                    "ShipCountry": "PH",
                    "ShipCity": "Batarasa",
                    "ShipName": "Gibson Inc",
                    "ShipAddress": "948 Roxbury Center",
                    "CompanyEmail": "smatitiaho24@dailymotion.com",
                    "CompanyAgent": "Skippy Matitiaho",
                    "CompanyName": "Monahan, Haley and Murphy",
                    "Currency": "PHP",
                    "Notes": "sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius",
                    "Department": "Jewelery",
                    "Website": "printfriendly.com",
                    "Latitude": 8.5015747,
                    "Longitude": 117.3557854,
                    "ShipDate": "1\/12\/2017",
                    "PaymentDate": "2016-09-07 16:34:55",
                    "TimeZone": "Asia\/Manila",
                    "Status": 1,
                    "Type": 3,
                    "TotalPayment": "9,541.82 PHP"
                },
                {
                    "RecordID": 330,
                    "OrderID": "54868-5303",
                    "ShipCountry": "PH",
                    "ShipCity": "Sillon",
                    "ShipName": "Balistreri Group",
                    "ShipAddress": "8203 Truax Center",
                    "CompanyEmail": "kvickarman95@storify.com",
                    "CompanyAgent": "Kipp Vickarman",
                    "CompanyName": "Kerluke and Sons",
                    "Currency": "PHP",
                    "Notes": "lobortis ligula sit amet eleifend pede libero quis orci nullam molestie",
                    "Department": "Clothing",
                    "Website": "vkontakte.ru",
                    "Latitude": 11.186148,
                    "Longitude": 123.7487563,
                    "ShipDate": "1\/14\/2017",
                    "PaymentDate": "2017-05-16 18:29:45",
                    "TimeZone": "Asia\/Manila",
                    "Status": 6,
                    "Type": 1,
                    "TotalPayment": "8,300.97 PHP"
                },
                {
                    "RecordID": 51,
                    "OrderID": "49884-659",
                    "ShipCountry": "ID",
                    "ShipCity": "Atap",
                    "ShipName": "Blanda Group",
                    "ShipAddress": "1 Monica Alley",
                    "CompanyEmail": "sjackes1e@reuters.com",
                    "CompanyAgent": "Shelagh Jackes",
                    "CompanyName": "Schiller Inc",
                    "Currency": "IDR",
                    "Notes": "iaculis justo in hac habitasse platea dictumst etiam faucibus cursus",
                    "Department": "Jewelery",
                    "Website": "forbes.com",
                    "Latitude": 3.8152026,
                    "Longitude": 117.1147095,
                    "ShipDate": "1\/15\/2016",
                    "PaymentDate": "2016-06-24 03:01:19",
                    "TimeZone": "Asia\/Makassar",
                    "Status": 2,
                    "Type": 1,
                    "TotalPayment": "8,397.18 IDR"
                },
                {
                    "RecordID": 313,
                    "OrderID": "23155-179",
                    "ShipCountry": "PA",
                    "ShipCity": "Potrero Grande",
                    "ShipName": "Olson, Schmeler and Little",
                    "ShipAddress": "3 Bartillon Place",
                    "CompanyEmail": "cgrandison8o@auda.org.au",
                    "CompanyAgent": "Corliss Grandison",
                    "CompanyName": "Mills-Beatty",
                    "Currency": "PAB",
                    "Notes": "egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend",
                    "Department": "Clothing",
                    "Website": "mlb.com",
                    "Latitude": 8.881634,
                    "Longitude": -79.8268729,
                    "ShipDate": "1\/16\/2016",
                    "PaymentDate": "2017-12-06 10:30:59",
                    "TimeZone": "America\/Panama",
                    "Status": 3,
                    "Type": 2,
                    "TotalPayment": "85,706.89 PAB"
                },
                {
                    "RecordID": 153,
                    "OrderID": "53341-515",
                    "ShipCountry": "MD",
                    "ShipCity": "Saharna",
                    "ShipName": "Leffler, Sawayn and Denesik",
                    "ShipAddress": "07247 Del Sol Hill",
                    "CompanyEmail": "fshank48@spotify.com",
                    "CompanyAgent": "Findley Shank",
                    "CompanyName": "Reilly LLC",
                    "Currency": "MDL",
                    "Notes": "dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo",
                    "Department": "Industrial",
                    "Website": "discuz.net",
                    "Latitude": 47.6949791,
                    "Longitude": 28.9654659,
                    "ShipDate": "1\/17\/2016",
                    "PaymentDate": "2017-01-05 15:53:50",
                    "TimeZone": "Europe\/Chisinau",
                    "Status": 6,
                    "Type": 1,
                    "TotalPayment": "993,295.17 MDL"
                },
                {
                    "RecordID": 112,
                    "OrderID": "50580-198",
                    "ShipCountry": "PT",
                    "ShipCity": "Loureiro",
                    "ShipName": "Labadie, Hegmann and Jones",
                    "ShipAddress": "9986 Arapahoe Place",
                    "CompanyEmail": "bglaister33@bbb.org",
                    "CompanyAgent": "Baxie Glaister",
                    "CompanyName": "Stark, Haley and Koepp",
                    "Currency": "EUR",
                    "Notes": "suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas",
                    "Department": "Tools",
                    "Website": "apple.com",
                    "Latitude": 41.4808684,
                    "Longitude": -8.3624629,
                    "ShipDate": "1\/17\/2016",
                    "PaymentDate": "2016-04-24 01:53:42",
                    "TimeZone": "Europe\/Lisbon",
                    "Status": 3,
                    "Type": 3,
                    "TotalPayment": "9,705.78 EUR"
                },
                {
                    "RecordID": 29,
                    "OrderID": "30142-106",
                    "ShipCountry": "RU",
                    "ShipCity": "Loukhi",
                    "ShipName": "Klein-Streich",
                    "ShipAddress": "61 Cascade Plaza",
                    "CompanyEmail": "mgallamores@businesswire.com",
                    "CompanyAgent": "Minor Gallamore",
                    "CompanyName": "Huels-Strosin",
                    "Currency": "RUB",
                    "Notes": "sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique",
                    "Department": "Beauty",
                    "Website": "epa.gov",
                    "Latitude": 66.0733463,
                    "Longitude": 33.0544476,
                    "ShipDate": "1\/17\/2016",
                    "PaymentDate": "2016-03-09 04:40:38",
                    "TimeZone": "Europe\/Moscow",
                    "Status": 2,
                    "Type": 2,
                    "TotalPayment": "931,956.17 RUB"
                },
                {
                    "RecordID": 135,
                    "OrderID": "49348-387",
                    "ShipCountry": "FR",
                    "ShipCity": "Sens",
                    "ShipName": "Collins, Hackett and Vandervort",
                    "ShipAddress": "594 Hanover Crossing",
                    "CompanyEmail": "tkiezler3q@live.com",
                    "CompanyAgent": "Tommy Kiezler",
                    "CompanyName": "Eichmann and Sons",
                    "Currency": "EUR",
                    "Notes": "etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi",
                    "Department": "Toys",
                    "Website": "instagram.com",
                    "Latitude": 48.1903349,
                    "Longitude": 3.2995005,
                    "ShipDate": "1\/18\/2017",
                    "PaymentDate": "2016-12-28 03:56:57",
                    "TimeZone": "Europe\/Paris",
                    "Status": 2,
                    "Type": 2,
                    "TotalPayment": "811,814.44 EUR"
                }
            ]
        }