FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Kitabisa

API documentation for Kitabisa White Label

## Auth [/auth]

### Register [POST /auth/register]

+ Request (application/json)

        {
            "name": "User Skyshi",
            "email": "user@skyshi.com"
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {
                "token": "b78f3ec3494ba1a1809c918efff8b21f"
            }
        }

### Account Activation [POST /auth/register/activation]

+ Request (application/json)

        {
            "token": "b78f3ec3494ba1a1809c918efff8b21f",
            "password": "12345678"
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {}
        }

### Login [POST /auth/login]

+ Request (application/json)

        {
            "email": "user@skyshi.com",
            "password": "12345678"
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {}
        }

### Login Social [POST /auth/login/social]

+ Request (application/json)

        {
            "provider_name": "Facebook",
            "provider_uid": "12345678",
            "access_token": "EAAViKAqZCMswBAM1UqlZBZAF"
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {
                "_id": "5a67f684e1f7485ff03b2f6b",
                "name": "User Skyshi",
                "email": "user@skyshi.com"
                "phone": "081222333444",
                "photo_profile": "url",
                "location": "id",
                "address": "Tampomas no 9, Sleman"
            }
        }

### Forgot Password [POST /auth/password/forgot]

+ Request (application/json)

        {
            "email": "user@skyshi.com"
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {}
        }

### Reset Password [POST /auth/password/reset]

+ Request (application/json)

        {
            "token": "b78f3ec3494ba1a1809c918efff8b21f",
            "password": "12345678"
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {}
        }

## Campaign [/campaigns]

### Create Campaign [POST]

+ Request (application/json)

        {
            "title": "Bencana alam Tambora",
            "link": "https://kitabisa.com/bencana-alam-tambora",
            "target": 500000000,
            "deadline": 1516781054,
            "category_id": "5a67f684e1f7485ff03b2f6b",
            "location": "Sleman, Yogyakarta",
            "main_image": "",
            "main_video": "https://youtube.com",
            "short_description": "Lorem ipsum dolor sit amet",
            "description": "Lorem ipsum dolor sit amet",
            "is_verified": false,
            "is_active": false
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {}
        }

### List Campaign [GET /campaigns?page={page}&limit={limit}&q={query}&category_id={category_id}]

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": [
                {
                    "title": "Bencana alam Tambora",
                    "link": "https://kitabisa.com/bencana-alam-tambora",
                    "target": 500000000,
                    "deadline": 1516781054,
                    "category_id": "5a67f684e1f7485ff03b2f6b",
                    "location": "Sleman, Yogyakarta",
                    "main_image": "",
                    "main_video": "https://youtube.com",
                    "short_description": "Lorem ipsum dolor sit amet",
                    "description": "Lorem ipsum dolor sit amet",
                    "is_verified": true,
                    "is_active": true
                }
            ]
        }

### Detail Campaign [GET /campaigns/id={id}]

+ Parameters
    + id: "5a67f684e1f7485ff03b2f6b" (string)

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {
                "_id": "5a67f684e1f7485ff03b2f6b",
                "title": "Bencana alam Tambora",
                "link": "https://kitabisa.com/bencana-alam-tambora",
                "target": 500000000,
                "deadline": 1516781054,
                "category_id": "5a67f684e1f7485ff03b2f6b",
                "location": "Sleman, Yogyakarta",
                "main_image": "",
                "main_video": "https://youtube.com",
                "short_description": "Lorem ipsum dolor sit amet",
                "description": "Lorem ipsum dolor sit amet",
                "is_verified": true,
                "is_active": true
            }
        }

### Update Campaign [PUT /campaigns/id={id}]

+ Parameters
    + id: "5a67f684e1f7485ff03b2f6b" (string)

+ Request (application/json)

        {
            "title": "Bencana alam Tambora",
            "link": "https://kitabisa.com/bencana-alam-tambora",
            "target": 500000000,
            "deadline": 1516781054,
            "category_id": "5a67f684e1f7485ff03b2f6b",
            "location": "Sleman, Yogyakarta",
            "main_image": "",
            "main_video": "https://youtube.com",
            "short_description": "Lorem ipsum dolor sit amet",
            "description": "Lorem ipsum dolor sit amet",
            "is_verified": true,
            "is_active": false
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {}
        }

### Delete Campaign [DELETE /campaigns/id={id}]

+ Parameters
    + id: "5a67f684e1f7485ff03b2f6b" (string)

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {}
        }

### Campaign Donate [POST /campaigns/id={id}/donate]

+ Parameters
    + id: "5a67f684e1f7485ff03b2f6b" (string)

+ Request (application/json)

        {
            "amount": "Bencana alam Tambora",
            "comment": "https://kitabisa.com/bencana-alam-tambora",
            "payment_method_id": 1
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {}
        }

## Campaign [/payments]

### Callback API [POST]

+ Request (application/json)

        {
            "campaign_id": "5a67f684e1f7485ff03b2f6b",
            "user_id": "5a67f684e1f7485ff03b2f6b",
            "status": "SUCCESS"
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {}
        }
        
## User [/user]

### Get Profile [GET]

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {
                "_id": "5a67f684e1f7485ff03b2f6b",
                "name": "User Skyshi",
                "email": "user@skyshi.com"
                "phone": "081222333444",
                "photo_profile": "url",
                "location": "id",
                "address": "Tampomas no 9, Sleman"
            }
        }

### Update Profile [PUT]

+ Request (application/json)

        {
            "name": "User Skyshi",
            "phone": "081222333444",
            "photo_profile": "",
            "location": "id",
            "address": "Tampomas no 9, Sleman"
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {}
        }

### Get Donations [GET /user/donations?page={page}&limit={limit}&q={query}&category_id={category_id}]

+ Parameters
    + page: 1 (number)
    + limit: 10 (number)
    + query: "bencana" (string)
    + category_id: "5a67f684e1f7485ff03b2f6b" (string)

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": [
                {
                    "campaign_id": "5a67f684e1f7485ff03b2f6b",
                    "campaign": {
                        "title": "Bencana alam tambora"
                    },
                    "amount": 10000,
                    "message": "Semoga Berkah"
                }
            ]
        }
        
## Generator Example [/generator]

### Auth [POST /generator/auth/login]

+ Request (application/json)

        {
            "username": "skyshi",
            "password": "skyshi"
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {
                "name": "admin",
                "email": "developer@skyshi.com",
                "token" : "23423sfsdfsvfvfve223r32rdvvdfvdv"
            }
        }

### Book List [GET /generator/books?filter={filter}&pagination={pagination}&sort={sort}]
+ Parameters
    + filter: {"q":"search"} (object)
    + pagination: {"page": 1, "perPage": 10} (object)
    + sort: {"field": "name", "order":"ASC"} (object)

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": [
                {
                    "name" : "book",
                    "image" : "http://lorempixel.com/400/200",
                    "category": {
                        "id" : "1",
                        "name" : "novel"
                    },
                    "writer" : {
                        "id" : "1",
                        "name" : "john doe"
                    },
                    "created_at" : 223432423,
                    "updated_at" : 342342424
                },
                {
                    "name" : "book",
                    "image" : "http://lorempixel.com/400/200",
                    "category": {
                        "id" : "1",
                        "name" : "novel"
                    },
                    "writer" : {
                        "id" : "1",
                        "name" : "john doe"
                    },
                    "created_at" : 223432423,
                    "updated_at" : 342342424
                },
                {
                    "name" : "book",
                    "image" : "http://lorempixel.com/400/200",
                    "category": {
                        "id" : "1",
                        "name" : "novel"
                    },
                    "writer" : {
                        "id" : "1",
                        "name" : "john doe"
                    },
                    "created_at" : 223432423,
                    "updated_at" : 342342424
                },
                {
                    "name" : "book",
                    "image" : "http://lorempixel.com/400/200",
                    "category": {
                        "id" : "1",
                        "name" : "novel"
                    },
                    "writer" : {
                        "id" : "1",
                        "name" : "john doe"
                    },
                    "created_at" : 223432423,
                    "updated_at" : 342342424
                },
                {
                    "name" : "book",
                    "image" : "http://lorempixel.com/400/200",
                    "category": {
                        "id" : "1",
                        "name" : "novel"
                    },
                    "writer" : {
                        "id" : "1",
                        "name" : "john doe"
                    },
                    "created_at" : 223432423,
                    "updated_at" : 342342424
                },
                {
                    "name" : "book",
                    "image" : "http://lorempixel.com/400/200",
                    "category": {
                        "id" : "1",
                        "name" : "novel"
                    },
                    "writer" : {
                        "id" : "1",
                        "name" : "john doe"
                    },
                    "created_at" : 223432423,
                    "updated_at" : 342342424
                },
                {
                    "name" : "book",
                    "image" : "http://lorempixel.com/400/200",
                    "category": {
                        "id" : "1",
                        "name" : "novel"
                    },
                    "writer" : {
                        "id" : "1",
                        "name" : "john doe"
                    },
                    "created_at" : 223432423,
                    "updated_at" : 342342424
                },
                {
                    "name" : "book",
                    "image" : "http://lorempixel.com/400/200",
                    "category": {
                        "id" : "1",
                        "name" : "novel"
                    },
                    "writer" : {
                        "id" : "1",
                        "name" : "john doe"
                    },
                    "created_at" : 223432423,
                    "updated_at" : 342342424
                },
                {
                    "name" : "book",
                    "image" : "http://lorempixel.com/400/200",
                    "category": {
                        "id" : "1",
                        "name" : "novel"
                    },
                    "writer" : {
                        "id" : "1",
                        "name" : "john doe"
                    },
                    "created_at" : 223432423,
                    "updated_at" : 342342424
                },
                {
                    "name" : "book",
                    "image" : "http://lorempixel.com/400/200",
                    "category": {
                        "id" : "1",
                        "name" : "novel"
                    },
                    "writer" : {
                        "id" : "1",
                        "name" : "john doe"
                    },
                    "created_at" : 223432423,
                    "updated_at" : 342342424
                }
            ]
        }

### Book Detail [GET /generator/books/{id}]
+ Parameters
    + id: "1" (string)

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {
                "name" : "book",
                "image" : "http://lorempixel.com/400/200",
                "description":"dummy text",
                "category": {
                    "id" : "1",
                    "name" : "novel"
                },
                "writer" : {
                    "id" : "1",
                    "name" : "john doe"
                },
                "created_at" : 223432423,
                "updated_at" : 342342424
            }
        }


### Book Update [PUT /generator/books/{id}]
+ Parameters
    + id: "1" (string)
    
+ Request (application/json)

        {
            "name": "book update",
            "image" : "http://lorempixel.com/400/200",
            "desc" : "test",
            "category_id": "2",
            "writer_id": "2"
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Update Success",
            "data": {}
        }

### Book Delete [DELETE /generator/books/{id}]
+ Parameters
    + id: "1" (string)

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Delete Success",
            "data": {}
        }
        
### Category List [GET /generator/categories]

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": [
                {
                    "id": "1",
                    "name": "category 1",
                },
                {
                    "id": "2",
                    "name": "category 2",
                },
                {
                    "id": "3",
                    "name": "category 3",
                },
                {
                    "id": "4",
                    "name": "category 4",
                },
                {
                    "id": "5",
                    "name": "category 5",
                }
            ]
        }
        
### Writer List [GET /generator/writers]

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": [
                {
                    "id": "1",
                    "name": "write 1",
                },
                {
                    "id": "2",
                    "name": "write 2",
                },
                {
                    "id": "3",
                    "name": "write 3",
                },
                {
                    "id": "4",
                    "name": "write 4",
                },
                {
                    "id": "5",
                    "name": "write 5",
                }
            ]
        }