FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Kitabisa

API documentation for Kitabisa White Label

## Auth [/auth]

### Register [POST /auth/register]

+ Request (application/json)

        {
            "name": "User Skyshi",
            "email": "user@skyshi.com"
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {}
        }

### Account Activation [POST /auth/register/activation]

+ Request (application/json)

        {
            "token": "b78f3ec3494ba1a1809c918efff8b21f",
            "password": "12345678"
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {}
        }
        
## User [/user]

### Get Profile [GET]

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {
                "name": "User Skyshi",
                "email": "user@skyshi.com"
                "phone": "081222333444",
                "photo_profile": "url",
                "location": "id",
                "address": "Tampomas no 9, Sleman"
            }
        }

### Update Profile [PUT]

+ Request (application/json)

        {
            "name": "User Skyshi",
            "phone": "081222333444",
            "photo_profile": "",
            "location": "id",
            "address": "Tampomas no 9, Sleman"
        }

+ Response 200 (application/json)

        {
            "code": 200,
            "status": true,
            "message": "Success",
            "data": {}
        }